#' Simulated ITED-like dichotomous responses (Brennan, 1998)
#'
#' A simulated person-by-item matrix of dichotomously scored responses
#' built to mimic the summary characteristics of the ITED Vocabulary
#' Test example analysed in Brennan (1998, p. 314; Figure 1, p. 315).
#' It is intended as a self-contained illustration dataset for the
#' single-facet, person-by-item crossed Generalizability Theory design
#' implemented in \code{\link{csem_gt}}.
#'
#' \strong{These are simulated data, not the original ITED data.} The
#' real Iowa Tests of Educational Development Vocabulary data described
#' by Feldt, Forsyth, Ansley, and Alnot (1993, 1994) are not publicly
#' available. \code{iowa_like} was generated from a Rasch (1PL) model
#' whose parameters were calibrated so that the ANOVA-based mean
#' absolute and relative error variances reproduce the values Brennan
#' reports: \eqn{\bar{\sigma}^2(\Delta) \approx .00514} and
#' \eqn{\bar{\sigma}^2(\delta) \approx .00475}. The matrix uses
#' \eqn{A = 3000} simulated persons, matching Brennan's own use of
#' 3,000 generated examinees for the absolute-error illustration. The
#' full, seeded generation script is in \code{data-raw/make_iowa_like.R}.
#'
#' @format An integer matrix with 3000 rows (persons) and 40 columns
#'   (items). Each entry is 0 or 1 (incorrect / correct). Columns are
#'   named \code{item01}, \code{item02}, ..., \code{item40}.
#'
#' @source Simulated to match the summary statistics of the ITED
#'   Vocabulary Test example in Brennan, R. L. (1998). Raw-score
#'   conditional standard errors of measurement in generalizability
#'   theory. \emph{Applied Psychological Measurement, 22}(4), 307-331.
#'   The underlying instrument is described in Feldt, L. S., Forsyth,
#'   R. A., Ansley, T. N., & Alnot, S. D. (1993, 1994). \emph{Iowa
#'   Tests of Educational Development}. Riverside.
#'
#' @references
#' Brennan, R. L. (1998). Raw-score conditional standard errors of
#' measurement in generalizability theory. \emph{Applied Psychological
#' Measurement, 22}(4), 307-331.
#'
#' @examples
#' data(iowa_like)
#' dim(iowa_like)
#' iowa_like[1:5, 1:6]
#'
#' ## Relative conditional SEM, 'full' estimator (the default),
#' ## reproducing the kind of dispersion seen in Brennan (1998),
#' ## Figure 1b/1d.
#' \donttest{
#' fit <- csem_gt(iowa_like, error_type = "relative", method = "full")
#' fit
#' plot(fit)
#' }
"iowa_like"


#' Simulated IPIP-10-like Likert responses
#'
#' A simulated person-by-item matrix of Likert-scaled (1-5) responses
#' built to mimic the qualitative features of a short, positively
#' oriented Big-Five Conscientiousness subscale -- in particular, the
#' Conscientiousness items of the IPIP-50 inventory (Goldberg, 1992;
#' Goldberg et al., 2006). It is intended as a self-contained
#' illustration dataset for the polytomous Likert use case in the
#' single-facet, person-by-item crossed Generalizability Theory design
#' implemented in \code{\link{csem_gt}}.
#'
#' \strong{These are simulated data, not real IPIP-50 responses.}
#' \code{ipip_like} was generated by drawing independent normal person,
#' item, and residual effects under the random-effects model that
#' Generalizability Theory assumes for the \eqn{p \times i} design, and
#' then rounding and clipping the resulting scores to the 1-5 Likert
#' metric. The pre-truncation variance components are inflated to
#' absorb the contraction induced by the clip-and-round step, so that
#' the post-truncation ANOVA estimates approximate the targets
#' \eqn{\sigma^2(p) \approx 0.434}, \eqn{\sigma^2(i) \approx 0.136},
#' and \eqn{\sigma^2(pi) \approx 1.000}, with generalizability
#' coefficient \eqn{E\rho^2 \approx 0.81}. These targets are
#' representative of the Conscientiousness subscale of the IPIP-50
#' dataset distributed by the Open-Source Psychometrics Project (n.d.)
#' and can be reproduced by any user with access to that public
#' dataset via a one-way \eqn{p \times i} ANOVA. The matrix uses
#' \eqn{A = 2{,}000} simulated persons and \eqn{I = 10} items, with all
#' items oriented positively (any reverse-keying is assumed already
#' applied so that higher scores indicate higher Conscientiousness).
#' The full, seeded generation script is in
#' \code{data-raw/make_ipip_like.R}.
#'
#' @format An integer matrix with 2000 rows (persons) and 10 columns
#'   (items). Each entry is an integer in \eqn{\{1, 2, 3, 4, 5\}}.
#'   Columns are named \code{item01}, \code{item02}, ..., \code{item10}.
#'
#' @source Simulated to be broadly comparable to the Conscientiousness
#'   subscale of the IPIP-50 inventory, as administered in the public
#'   dataset of the Open-Source Psychometrics Project
#'   (\url{https://openpsychometrics.org/_rawdata/}). The underlying
#'   instrument is described in Goldberg, L. R. (1992) and
#'   Goldberg, L. R., Johnson, J. A., Eber, H. W., Hogan, R., Ashton,
#'   M. C., Cloninger, C. R., & Gough, H. G. (2006).
#'
#' @references
#' Goldberg, L. R. (1992). The development of markers for the Big-Five
#' factor structure. \emph{Psychological Assessment, 4}(1), 26-42.
#'
#' Goldberg, L. R., Johnson, J. A., Eber, H. W., Hogan, R., Ashton,
#' M. C., Cloninger, C. R., & Gough, H. G. (2006). The International
#' Personality Item Pool and the future of public-domain personality
#' measures. \emph{Journal of Research in Personality, 40}(1), 84-96.
#'
#' Open-Source Psychometrics Project. (n.d.). \emph{Raw data}.
#' \url{https://openpsychometrics.org/_rawdata/}
#'
#' @examples
#' data(ipip_like)
#' dim(ipip_like)
#' ipip_like[1:5, 1:6]
#'
#' \donttest{
#' fit <- csem_gt(ipip_like, error_type = "relative", method = "full",
#'                smoother = "polynomial")
#' fit
#' plot(fit, plot_type = "both", cibands = "model")
#' }
"ipip_like"
